// PDF Export Utility for SEO Reports

export interface SEOReportData {
  title: string;
  description: string;
  tags: string[];
  hashtags: string[];
  score: number;
  grade: string;
  timestamp: string;
  recommendations: string[];
}

export const generateSEOReportHTML = (data: SEOReportData): string => {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>SEO Analysis Report - ${data.title}</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      max-width: 800px;
      margin: 40px auto;
      padding: 20px;
      background: #f5f5f5;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 30px;
      border-radius: 10px;
      text-align: center;
      margin-bottom: 30px;
    }
    .score-circle {
      width: 150px;
      height: 150px;
      border-radius: 50%;
      background: white;
      display: flex;
      align-items: center;
      justify-content: center;
      margin: 20px auto;
      font-size: 48px;
      font-weight: bold;
      color: ${data.score >= 80 ? '#10b981' : data.score >= 60 ? '#f59e0b' : '#ef4444'};
    }
    .section {
      background: white;
      padding: 20px;
      border-radius: 10px;
      margin-bottom: 20px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .section h2 {
      color: #667eea;
      border-bottom: 2px solid #667eea;
      padding-bottom: 10px;
      margin-bottom: 15px;
    }
    .tag {
      display: inline-block;
      background: #e0e7ff;
      color: #4338ca;
      padding: 5px 12px;
      border-radius: 15px;
      margin: 5px;
      font-size: 14px;
    }
    .recommendation {
      background: #fef3c7;
      border-left: 4px solid #f59e0b;
      padding: 12px;
      margin: 10px 0;
      border-radius: 4px;
    }
    .footer {
      text-align: center;
      color: #666;
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🎥 ContentCraft AI</h1>
    <p>SEO Analysis Report</p>
    <div class="score-circle">${data.score}</div>
    <p style="font-size: 24px; margin: 10px 0;">Grade: ${data.grade}</p>
    <p style="font-size: 14px; opacity: 0.9;">${data.timestamp}</p>
  </div>

  <div class="section">
    <h2>📝 Video Title</h2>
    <p style="font-size: 18px; font-weight: 600;">${data.title}</p>
    <p style="color: #666; font-size: 14px;">Length: ${data.title.length} characters</p>
  </div>

  <div class="section">
    <h2>📄 Description</h2>
    <p style="line-height: 1.6;">${data.description}</p>
    <p style="color: #666; font-size: 14px;">Length: ${data.description.length} characters</p>
  </div>

  <div class="section">
    <h2>🏷️ Tags (${data.tags.length})</h2>
    ${data.tags.map(tag => `<span class="tag">${tag}</span>`).join('')}
  </div>

  <div class="section">
    <h2>#️⃣ Hashtags (${data.hashtags.length})</h2>
    ${data.hashtags.map(tag => `<span class="tag">${tag}</span>`).join('')}
  </div>

  <div class="section">
    <h2>💡 Recommendations</h2>
    ${data.recommendations.map(rec => `<div class="recommendation">${rec}</div>`).join('')}
  </div>

  <div class="footer">
    <p><strong>Generated by ContentCraft AI</strong></p>
    <p>Powered by Chrome Built-in AI APIs</p>
    <p style="font-size: 12px; color: #999;">© 2025 ContentCraft AI. All rights reserved.</p>
  </div>
</body>
</html>
  `;
};

export const exportToPDF = (data: SEOReportData) => {
  const html = generateSEOReportHTML(data);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `seo-report-${Date.now()}.html`;
  a.click();
  URL.revokeObjectURL(url);
};

export const exportToCSV = (data: SEOReportData) => {
  const csv = `
"SEO Analysis Report"
"Generated","${data.timestamp}"
""
"Title","${data.title.replace(/"/g, '""')}"
"Description","${data.description.replace(/"/g, '""')}"
"Score","${data.score}"
"Grade","${data.grade}"
""
"Tags"
${data.tags.map(tag => `"${tag}"`).join('\n')}
""
"Hashtags"
${data.hashtags.map(tag => `"${tag}"`).join('\n')}
""
"Recommendations"
${data.recommendations.map(rec => `"${rec.replace(/"/g, '""')}"`).join('\n')}
  `.trim();

  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `seo-report-${Date.now()}.csv`;
  a.click();
  URL.revokeObjectURL(url);
};
